server:
  port: 8080

spring:
  application:
    name: regulatory-policy-alignment

  datasource:
    url: jdbc:mysql://mysql:3306/policy_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

  data:
    redis:
      host: redis
      port: 6379

  mail:
    host: mailhog
    port: 1025

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always